/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.patient;
import backend.Doctor;
import backend.DoctorDirectory;
import backend.patientdirectory;
import backend.personDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author sej
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    static patientdirectory patientdirect;
    static DoctorDirectory docdirect;
    public LoginFrame() {
        initComponents();
        personDirectory.persondirect.add(personDirectory.person1());

     }
public LoginFrame(patientdirectory patientdirect){
    initComponents();
    LoginFrame.patientdirect = patientdirect;
}
    public LoginFrame(DoctorDirectory docdirect) {
        initComponents();
        LoginFrame.docdirect= docdirect;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLoginPage = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLoginPage.setBackground(new java.awt.Color(153, 153, 153));
        panelLoginPage.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Page"));
        panelLoginPage.setForeground(new java.awt.Color(153, 153, 153));

        lblEmail.setBackground(new java.awt.Color(102, 102, 102));
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setText("Email ID:");

        lblPassword.setText("Password:");

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginPageLayout = new javax.swing.GroupLayout(panelLoginPage);
        panelLoginPage.setLayout(panelLoginPageLayout);
        panelLoginPageLayout.setHorizontalGroup(
            panelLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginPageLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginPageLayout.createSequentialGroup()
                        .addGroup(panelLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail)
                            .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginPageLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75)))
                .addGap(76, 76, 76))
        );
        panelLoginPageLayout.setVerticalGroup(
            panelLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginPageLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(panelLoginPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtEmail.getText();
        String password = new String(pwdPassword.getPassword());

        MainFrame mainFrame = new MainFrame();
        if(username.equals("system_admin") && password.equals("syspwd")){
            mainFrame.setVisible(true);
            setVisible(false);
            mainFrame.AssignMenu("system_admin");
        }
        else if(username.equals("hospital_admin") && password.equals("hosppwd")){
            mainFrame.setVisible(true);
            setVisible(false);
            mainFrame.AssignMenu("hospital_admin");
        }
        else if(username.equals("community_admin") && password.equals("commpwd")){
            mainFrame.setVisible(true);
            setVisible(false);
            mainFrame.AssignMenu("community_admin");
        }
       else
        {
            int validUser=0;
            System.out.println("Checking User");
            for(patient patient: patientdirectory.getpatientdirect()){
                if(username.equals(patient.getEmailId())&& password.equals(patient.getPatientpwd())){
                    patientLoggedinframe patientLoggedIn = new patientLoggedinframe(username);
                    patientLoggedIn.setVisible(true);
                    setVisible(false);
                    validUser=1;
                }
            }
         for(patient p: patientdirectory.getpatientdirect()){
                if(username.equals(p.getPwd()) && password.equals(p.getPwd())){
                    mainFrame.setVisible(true);
                    setVisible(false);
                    mainFrame.AssignMenu("system_admin");
                    validUser = 1;
                }     
            }
          for(Doctor doc: DoctorDirectory.getdocdirect()){
                if(username.equals(doc.getEmailId()) && password.equals(doc.getDocPwd())){
                    DoctorLoggedInPage docLoggedIn = new DoctorLoggedInPage(username);
                    docLoggedIn.setVisible(true);
                    setVisible(false);
                    validUser = 1;
                } 
         if(validUser == 0){
                System.out.println("#########");
                JOptionPane.showMessageDialog(null, "Invalid Account");
            }
          }
        } 
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JPanel panelLoginPage;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables

}