/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.patient;
import backend.patientdirectory;
import backend.person;
import java.util.Date;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.TableRowSorter;
import javax.swing.ButtonGroup;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sej
 */
public class Patientdashboards extends javax.swing.JFrame {
patientdirectory patientdirect;

    /**
     * Creates new form Patientdashboards
     */
    public Patientdashboards(patientdirectory patientdirect) {
        initComponents();
                this.patientdirect = patientdirect;
                patientTable();
                
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        patientHomeBtn = new javax.swing.JButton();
        patientLogoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        personModificationTab = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        personPersonalDetails = new javax.swing.JPanel();
        patientName = new javax.swing.JTextField();
        patientNameLbl = new javax.swing.JLabel();
        patientContactLbl = new javax.swing.JLabel();
        patientContact = new javax.swing.JTextField();
        patientPatientID = new javax.swing.JTextField();
        patientPatientIDLbl = new javax.swing.JLabel();
        patientGenderLbl = new javax.swing.JLabel();
        patientGenderCombo = new javax.swing.JComboBox<>();
        patientAge = new javax.swing.JTextField();
        patientPatientIDLbl1 = new javax.swing.JLabel();
        personAddressDetails = new javax.swing.JPanel();
        patientHouse = new javax.swing.JTextField();
        patientHouseLbl = new javax.swing.JLabel();
        patientStreetLbl = new javax.swing.JLabel();
        patientStreet = new javax.swing.JTextField();
        patientCity = new javax.swing.JTextField();
        patientCommunityLbl = new javax.swing.JLabel();
        patientCityLbl = new javax.swing.JLabel();
        patientCommunity = new javax.swing.JTextField();
        patientZipCodeLbl = new javax.swing.JLabel();
        patientState = new javax.swing.JTextField();
        patientStateLbl = new javax.swing.JLabel();
        patientZipCode = new javax.swing.JTextField();
        personMedicalDetails = new javax.swing.JPanel();
        patientBloodGroup = new javax.swing.JTextField();
        patientBloodGroupLbl = new javax.swing.JLabel();
        patientHeightLbl = new javax.swing.JLabel();
        patientHeight = new javax.swing.JTextField();
        patientWeightLbl = new javax.swing.JLabel();
        patientWeight = new javax.swing.JTextField();
        personAccountDetails = new javax.swing.JPanel();
        patientEmailID = new javax.swing.JTextField();
        patientEmailIDLbl = new javax.swing.JLabel();
        patientPswdLbl = new javax.swing.JLabel();
        patientRepswdLbl = new javax.swing.JLabel();
        patientPassword = new javax.swing.JPasswordField();
        patientConfirmPswd = new javax.swing.JPasswordField();
        patientRegisterBtn = new javax.swing.JButton();
        personClearBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        modifyPatientName = new javax.swing.JTextField();
        patientNameLbl2 = new javax.swing.JLabel();
        patientContactLbl2 = new javax.swing.JLabel();
        modifyContact = new javax.swing.JTextField();
        modifyPatientEmailID = new javax.swing.JTextField();
        patientEmailIDLbl2 = new javax.swing.JLabel();
        patientGenderLbl2 = new javax.swing.JLabel();
        modifyAge = new javax.swing.JTextField();
        patientDOBLbl2 = new javax.swing.JLabel();
        patientAgeLbl2 = new javax.swing.JLabel();
        patientHouseLbl1 = new javax.swing.JLabel();
        modifyHouse = new javax.swing.JTextField();
        patientStreetLbl1 = new javax.swing.JLabel();
        modifyStreetName = new javax.swing.JTextField();
        patientCommunityLbl1 = new javax.swing.JLabel();
        modifyCommunity = new javax.swing.JTextField();
        patientCityLbl1 = new javax.swing.JLabel();
        modifyCity = new javax.swing.JTextField();
        patientStateLbl1 = new javax.swing.JLabel();
        modifyState = new javax.swing.JTextField();
        patientZipCodeLbl1 = new javax.swing.JLabel();
        modifyZipCode = new javax.swing.JTextField();
        patientBloodGroupLbl1 = new javax.swing.JLabel();
        modifyPatientBloodGrp = new javax.swing.JTextField();
        patientHeightLbl1 = new javax.swing.JLabel();
        modifyHeight = new javax.swing.JTextField();
        patientWeightLbl1 = new javax.swing.JLabel();
        modifyWeight = new javax.swing.JTextField();
        patientViewBtn = new javax.swing.JButton();
        patientUpdateBtn = new javax.swing.JButton();
        patientDeleteBtn = new javax.swing.JButton();
        modifyPatientGenderCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        patientHomeBtn.setText("Home");
        patientHomeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientHomeBtnActionPerformed(evt);
            }
        });

        patientLogoutBtn.setText("Logout");
        patientLogoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientLogoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setText("Patient Registration");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(patientHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262)
                .addComponent(jLabel1)
                .addGap(284, 284, 284)
                .addComponent(patientLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientLogoutBtn)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9))
        );

        personModificationTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        personPersonalDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 13))); // NOI18N

        patientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameActionPerformed(evt);
            }
        });

        patientNameLbl.setText("Name");

        patientContactLbl.setText("Contact");

        patientPatientIDLbl.setText("Patient ID");

        patientGenderLbl.setText("Gender");

        patientGenderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", "" }));
        patientGenderCombo.setSelectedIndex(-1);

        patientPatientIDLbl1.setText("Age");

        javax.swing.GroupLayout personPersonalDetailsLayout = new javax.swing.GroupLayout(personPersonalDetails);
        personPersonalDetails.setLayout(personPersonalDetailsLayout);
        personPersonalDetailsLayout.setHorizontalGroup(
            personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPersonalDetailsLayout.createSequentialGroup()
                .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personPersonalDetailsLayout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientContactLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientNameLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientGenderLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientPatientIDLbl1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personPersonalDetailsLayout.createSequentialGroup()
                        .addGap(0, 34, Short.MAX_VALUE)
                        .addComponent(patientPatientIDLbl)
                        .addGap(20, 20, 20)))
                .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientContact, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(patientAge, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(patientGenderCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(patientPatientID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        personPersonalDetailsLayout.setVerticalGroup(
            personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPersonalDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientNameLbl))
                .addGap(20, 20, 20)
                .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientContactLbl))
                .addGap(20, 20, 20)
                .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientPatientIDLbl))
                .addGap(18, 18, 18)
                .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientGenderLbl)
                    .addComponent(patientGenderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(personPersonalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientPatientIDLbl1)
                    .addComponent(patientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        personAddressDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 13))); // NOI18N

        patientHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientHouseActionPerformed(evt);
            }
        });

        patientHouseLbl.setText("House");

        patientStreetLbl.setText("Street");

        patientCommunityLbl.setText("Community");

        patientCityLbl.setText("City");

        patientCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientCommunityActionPerformed(evt);
            }
        });

        patientZipCodeLbl.setText("Zipcode");

        patientState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientStateActionPerformed(evt);
            }
        });

        patientStateLbl.setText("State");

        javax.swing.GroupLayout personAddressDetailsLayout = new javax.swing.GroupLayout(personAddressDetails);
        personAddressDetails.setLayout(personAddressDetailsLayout);
        personAddressDetailsLayout.setHorizontalGroup(
            personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personAddressDetailsLayout.createSequentialGroup()
                .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personAddressDetailsLayout.createSequentialGroup()
                        .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personAddressDetailsLayout.createSequentialGroup()
                                .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(personAddressDetailsLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(patientZipCodeLbl))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personAddressDetailsLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(patientStateLbl)))
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personAddressDetailsLayout.createSequentialGroup()
                                .addComponent(patientCityLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientState, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientCity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(personAddressDetailsLayout.createSequentialGroup()
                        .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personAddressDetailsLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(patientStreetLbl)
                                    .addComponent(patientHouseLbl)))
                            .addGroup(personAddressDetailsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(patientCommunityLbl)))
                        .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personAddressDetailsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(patientHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patientStreet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(personAddressDetailsLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(patientCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        personAddressDetailsLayout.setVerticalGroup(
            personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personAddressDetailsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientHouseLbl))
                .addGap(20, 20, 20)
                .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientStreetLbl))
                .addGap(23, 23, 23)
                .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientCommunityLbl)
                    .addComponent(patientCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personAddressDetailsLayout.createSequentialGroup()
                        .addComponent(patientStateLbl)
                        .addGap(18, 18, 18)
                        .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientZipCodeLbl)
                            .addComponent(patientZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personAddressDetailsLayout.createSequentialGroup()
                        .addGroup(personAddressDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientCityLbl)
                            .addComponent(patientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(patientState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGap(11, 11, 11))
        );

        personMedicalDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medical Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 13))); // NOI18N

        patientBloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBloodGroupActionPerformed(evt);
            }
        });

        patientBloodGroupLbl.setText("Blood Group");

        patientHeightLbl.setText("Height (in cms)");

        patientWeightLbl.setText("Weight (in lbs)");

        patientWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientWeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personMedicalDetailsLayout = new javax.swing.GroupLayout(personMedicalDetails);
        personMedicalDetails.setLayout(personMedicalDetailsLayout);
        personMedicalDetailsLayout.setHorizontalGroup(
            personMedicalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personMedicalDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personMedicalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientBloodGroupLbl)
                    .addGroup(personMedicalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(patientHeightLbl)
                        .addComponent(patientWeightLbl, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personMedicalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        personMedicalDetailsLayout.setVerticalGroup(
            personMedicalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personMedicalDetailsLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(personMedicalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientBloodGroupLbl))
                .addGap(20, 20, 20)
                .addGroup(personMedicalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientHeightLbl))
                .addGap(20, 20, 20)
                .addGroup(personMedicalDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientWeightLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        personAccountDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 13))); // NOI18N

        patientEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientEmailIDActionPerformed(evt);
            }
        });

        patientEmailIDLbl.setText("Email ID");

        patientPswdLbl.setText("Password");

        patientRepswdLbl.setText("Re-Pswd");

        patientPassword.setText("jPasswordField1");
        patientPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientPasswordActionPerformed(evt);
            }
        });

        patientConfirmPswd.setText("jPasswordField1");
        patientConfirmPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientConfirmPswdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personAccountDetailsLayout = new javax.swing.GroupLayout(personAccountDetails);
        personAccountDetails.setLayout(personAccountDetailsLayout);
        personAccountDetailsLayout.setHorizontalGroup(
            personAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personAccountDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(personAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientRepswdLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientPswdLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(patientEmailIDLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(personAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(patientEmailID)
                    .addComponent(patientPassword)
                    .addComponent(patientConfirmPswd, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        personAccountDetailsLayout.setVerticalGroup(
            personAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personAccountDetailsLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(personAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientEmailIDLbl)
                    .addComponent(patientEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(personAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientPswdLbl)
                    .addComponent(patientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(personAccountDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientRepswdLbl)
                    .addComponent(patientConfirmPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        patientRegisterBtn.setText("Register");
        patientRegisterBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientRegisterBtnActionPerformed(evt);
            }
        });

        personClearBtn.setText("Clear");
        personClearBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        personClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(personMedicalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(personPersonalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(patientRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(personAddressDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(personAccountDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(personClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personPersonalDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personAddressDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(personMedicalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personAccountDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        personModificationTab.addTab("Personal Details", jPanel4);

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Patient ID", "Contact ", "Email ID", "Gender", "Age", "Address", "Blood Grp", "Height", "Weight"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        patientTable.setAutoscrolls(false);
        jScrollPane2.setViewportView(patientTable);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modifications ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 3, 13))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N

        modifyPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPatientNameActionPerformed(evt);
            }
        });

        patientNameLbl2.setText("Name");

        patientContactLbl2.setText("Contact");

        patientEmailIDLbl2.setText("Email ID");

        patientGenderLbl2.setText("Gender");

        modifyAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyAgeActionPerformed(evt);
            }
        });

        patientDOBLbl2.setText("DOB");

        patientAgeLbl2.setText("Age");

        patientHouseLbl1.setText("House");

        modifyHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyHouseActionPerformed(evt);
            }
        });

        patientStreetLbl1.setText("Street");

        patientCommunityLbl1.setText("Community");

        modifyCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyCommunityActionPerformed(evt);
            }
        });

        patientCityLbl1.setText("City");

        patientStateLbl1.setText("State");

        modifyState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyStateActionPerformed(evt);
            }
        });

        patientZipCodeLbl1.setText("Zipcode");

        patientBloodGroupLbl1.setText("Blood Group");

        modifyPatientBloodGrp.setEditable(false);
        modifyPatientBloodGrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPatientBloodGrpActionPerformed(evt);
            }
        });

        patientHeightLbl1.setText("Height (in cms)");

        patientWeightLbl1.setText("Weight (in lbs)");

        modifyWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyWeightActionPerformed(evt);
            }
        });

        patientViewBtn.setText("View");
        patientViewBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientViewBtnActionPerformed(evt);
            }
        });

        patientUpdateBtn.setText("Update");
        patientUpdateBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientUpdateBtnActionPerformed(evt);
            }
        });

        patientDeleteBtn.setText("Delete");
        patientDeleteBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        patientDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientDeleteBtnActionPerformed(evt);
            }
        });

        modifyPatientGenderCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        modifyPatientGenderCombo.setSelectedIndex(-1);
        modifyPatientGenderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPatientGenderComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(patientContactLbl2))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(patientNameLbl2))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addComponent(patientDOBLbl2))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addGap(38, 38, 38)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(patientGenderLbl2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(patientAgeLbl2, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(patientEmailIDLbl2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modifyPatientEmailID, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(modifyPatientName, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(modifyContact, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(modifyAge, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(modifyPatientGenderCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(patientBloodGroupLbl1)
                                        .addGap(18, 18, 18)
                                        .addComponent(modifyPatientBloodGrp, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(patientHeightLbl1)
                                        .addGap(18, 18, 18)
                                        .addComponent(modifyHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(patientZipCodeLbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(patientStateLbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(patientWeightLbl1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modifyState, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modifyZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modifyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(patientStreetLbl1)
                                    .addComponent(patientHouseLbl1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(modifyStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modifyHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(patientCommunityLbl1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(modifyCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(patientCityLbl1)
                                    .addGap(18, 18, 18)
                                    .addComponent(modifyCity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(patientViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(patientUpdateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55)
                        .addComponent(patientDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifyHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientHouseLbl1))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifyStreetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientStreetLbl1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modifyPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNameLbl2))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modifyContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientContactLbl2))))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifyPatientEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientEmailIDLbl2))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientGenderLbl2)
                            .addComponent(modifyPatientGenderCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifyAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientAgeLbl2))
                        .addGap(22, 22, 22)
                        .addComponent(patientDOBLbl2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modifyCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientCommunityLbl1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientCityLbl1)
                            .addComponent(modifyCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(patientStateLbl1)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(modifyState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientZipCodeLbl1)
                            .addComponent(modifyZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(modifyWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(patientWeightLbl1))
                            .addComponent(modifyPatientBloodGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modifyHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientHeightLbl1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(patientBloodGroupLbl1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientViewBtn)
                    .addComponent(patientDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        personModificationTab.addTab("Modification", jPanel5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(personModificationTab, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personModificationTab)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientHomeBtnActionPerformed
        // TODO add your handling code here:

        MainFrame newMainFrame = new MainFrame();
        newMainFrame.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_patientHomeBtnActionPerformed

    private void patientLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientLogoutBtnActionPerformed
        LoginFrame newLoginPage = new LoginFrame();
        newLoginPage.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_patientLogoutBtnActionPerformed

    private void patientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameActionPerformed

    private void patientHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientHouseActionPerformed

    private void patientCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientCommunityActionPerformed

    private void patientStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientStateActionPerformed

    private void patientBloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientBloodGroupActionPerformed

    private void patientWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientWeightActionPerformed

    private void patientEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientEmailIDActionPerformed

    private void patientPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientPasswordActionPerformed

    private void patientConfirmPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientConfirmPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientConfirmPswdActionPerformed
        public void resetPatientForm(){ 
        patientName.setText("");
        patientContact.setText("");
        patientPatientID.setText("");
//        patientMaleRadioBtn.setSelected(false);
//        patientFemaleRadioBtn.setSelected(false);
//        patientOthersRadioBtn.setSelected(false);
       
        patientHouse.setText("");
        patientStreet.setText("");
        patientCommunity.setText("");
        patientCity.setText("");
        patientState.setText("");
        patientZipCode.setText("");
        patientAge.setText("");
//        patientDOB.setDate(null);
       
       
        patientBloodGroup.setText("");
        patientHeight.setText("");
        patientWeight.setText("");
//        patientAllergies.setText("");
       
        
        patientEmailID.setText("");
        patientPassword.setText("");
        patientConfirmPswd.setText("");
    }
    
    private void patientRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientRegisterBtnActionPerformed
        // TODO add your handling code here

        patient pat = new patient();
        pat.setName(patientName.getText());
        pat.setAge(Integer.parseInt(patientAge.getText()));
        pat.setEmailId(patientEmailID.getText());
        pat.setContactNo(Long.parseLong(patientContact.getText()));
        pat.setGender((String)patientGenderCombo.getSelectedItem());
//        pat.setDOB(patientDOB.getDate());

        pat.residence.communityName = patientCommunity.getText();
        pat.residence.houseNo = Integer.parseInt(patientHouse.getText());
        pat.residence.zip = Integer.parseInt(patientZipCode.getText());
        pat.residence.cityName = patientCity.getText();
        pat.residence.state = patientState.getText();
//        pat.residence.streetName = patientStreet.getText();
//        pat.setPatientAllergies(patientAllergies.getText());
        pat.setPatientId(Integer.parseInt(patientPatientID.getText()));
        pat.setBloodGroup(patientBloodGroup.getText());
        pat.setPatientHeight(Float.parseFloat(patientHeight.getText()));
        pat.setPatientWeight(Float.parseFloat(patientWeight.getText()));
        String pat_pwd = new String(patientPassword.getPassword());
        pat.setPwd(pat_pwd);

        JOptionPane.showMessageDialog(this,"Patient Successfully Added");

        resetPatientForm();
        patientTable();
    }//GEN-LAST:event_patientRegisterBtnActionPerformed

    private void personClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personClearBtnActionPerformed
        // TODO add your handling code here:
        resetPatientForm();
    }//GEN-LAST:event_personClearBtnActionPerformed

    private void modifyPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyPatientNameActionPerformed

    private void modifyAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyAgeActionPerformed

    private void modifyHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyHouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyHouseActionPerformed

    private void modifyCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyCommunityActionPerformed

    private void modifyStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyStateActionPerformed

    private void modifyPatientBloodGrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPatientBloodGrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyPatientBloodGrpActionPerformed

    private void modifyWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyWeightActionPerformed

    private void patientViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientViewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex=patientTable.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        patient selectedPatient=(patient)model.getValueAt(selectedRowIndex, 0);
        modifyPatientName.setText(selectedPatient.getName());
        patientPatientID.setText(String.valueOf(selectedPatient.patientId));
        modifyContact.setText(String.valueOf(selectedPatient.getContactNo()));
        modifyPatientGenderCombo.setSelectedItem((selectedPatient.getGender()));
        modifyHouse.setText(String.valueOf(selectedPatient.residence.getHouseNo()));
        modifyPatientEmailID.setText(selectedPatient.getEmailId());
        modifyCommunity.setText(selectedPatient.residence.getCommunityName());
        modifyAge.setText(String.valueOf(selectedPatient.getAge()));
//        modifyDOB.setDate(selectedPatient.getDOB());
        //        patientMaleRadioBtn.isSelected(selectedPatient.g());
        modifyCity.setText(selectedPatient.residence.getCityName());
        modifyState.setText(selectedPatient.residence.getState());
//        modifyStreetName.setText(selectedPatient.residence.getStreetName());
        modifyZipCode.setText(String.valueOf(selectedPatient.residence.getZip()));
        modifyPatientBloodGrp.setText(selectedPatient.getBloodGroup());
        modifyHeight.setText(String.valueOf(selectedPatient.getPatientHeight()));
        modifyWeight.setText(String.valueOf(selectedPatient.getPatientWeight()));
//        modifyAllergies.setText(selectedPatient.getPatientAllergies());
    }//GEN-LAST:event_patientViewBtnActionPerformed

    private void patientUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientUpdateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex1=patientTable.getSelectedRow();
        DefaultTableModel model1 = (DefaultTableModel) patientTable.getModel();
        patient selectedPatient=(patient)model1.getValueAt(selectedRowIndex1,0);
        selectedPatient.setName(patientName.getText());

        //        pt1.person.setAge(Integer.parseInt(patientAge.getText()));
        selectedPatient.setContactNo(Long.parseLong(modifyContact.getText()));
        selectedPatient.setGender(String.valueOf(modifyPatientGenderCombo.getSelectedItem()));
        selectedPatient.residence.communityName= (modifyCommunity.getText());
        selectedPatient.residence.houseNo= Integer.parseInt(modifyHouse.getText());
        selectedPatient.residence.zip = Integer.parseInt(modifyZipCode.getText());
        selectedPatient.residence.cityName = modifyCity.getText();
        selectedPatient.residence.state = modifyState.getText();
//        selectedPatient.residence.streetName = modifyStreetName.getText();
        selectedPatient.patientId = Integer.parseInt(patientPatientID.getText());
        selectedPatient.setEmailId(modifyPatientEmailID.getText());
        String patient_pwd=new String(patientPassword.getPassword());
        selectedPatient.setPwd(patient_pwd);
        selectedPatient.setBloodGroup(patientBloodGroup.getText());

        selectedPatient.setPatientHeight(Float.parseFloat(modifyHeight.getText()));
        selectedPatient.setPatientWeight(Float.parseFloat(modifyWeight.getText()));
//        selectedPatient.setPatientAllergies(modifyAllergies.getText());
        JOptionPane.showMessageDialog(this, "Person Successfully Updated");
        patientTable();
        ///
    }//GEN-LAST:event_patientUpdateBtnActionPerformed

    private void patientDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientDeleteBtnActionPerformed
        // TODO add your handling code here:

        int rowIndex = patientTable.getSelectedRow();
        if (rowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        //        System.out.print(model.getValueAt(rowIndex,0));
        patient selectedPatient =(patient)model.getValueAt(rowIndex,1);
        patientdirect.deletepatient(selectedPatient);

    }//GEN-LAST:event_patientDeleteBtnActionPerformed

    private void modifyPatientGenderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPatientGenderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyPatientGenderComboActionPerformed
public void patientTable(){
    
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();
        model.setRowCount(0);
        
        System.out.println("Done");
        for(patient pt: patientdirect.getpatientdirect()){
            Object[] row=new Object[10];
            row[0]=pt;
            row[1]=pt.getPatientId();
            row[2]=pt.getContactNo();
            row[3]=pt.getEmailId();
            row[4]=pt.getGender();
            row[5]=pt.getAge();
            row[6]=pt.residence.getHouseNo() + ", " +  pt.residence.getCommunityName() + ", " + pt.residence.getCityName() + ", " + pt.residence.getState()+ "," + pt.residence.getZip();
            row[7]=pt.getBloodGroup();
            row[8]=pt.getPatientHeight();
            row[9]=pt.getPatientWeight();
//            row[10]=pt.getpatientAllergies();
            model.addRow(row);
                    
        
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Patientdashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Patientdashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Patientdashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Patientdashboards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Patientdashboards().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField modifyAge;
    private javax.swing.JTextField modifyCity;
    private javax.swing.JTextField modifyCommunity;
    private javax.swing.JTextField modifyContact;
    private javax.swing.JTextField modifyHeight;
    private javax.swing.JTextField modifyHouse;
    private javax.swing.JTextField modifyPatientBloodGrp;
    private javax.swing.JTextField modifyPatientEmailID;
    private javax.swing.JComboBox<String> modifyPatientGenderCombo;
    private javax.swing.JTextField modifyPatientName;
    private javax.swing.JTextField modifyState;
    private javax.swing.JTextField modifyStreetName;
    private javax.swing.JTextField modifyWeight;
    private javax.swing.JTextField modifyZipCode;
    private javax.swing.JTextField patientAge;
    private javax.swing.JLabel patientAgeLbl2;
    private javax.swing.JTextField patientBloodGroup;
    private javax.swing.JLabel patientBloodGroupLbl;
    private javax.swing.JLabel patientBloodGroupLbl1;
    private javax.swing.JTextField patientCity;
    private javax.swing.JLabel patientCityLbl;
    private javax.swing.JLabel patientCityLbl1;
    private javax.swing.JTextField patientCommunity;
    private javax.swing.JLabel patientCommunityLbl;
    private javax.swing.JLabel patientCommunityLbl1;
    private javax.swing.JPasswordField patientConfirmPswd;
    private javax.swing.JTextField patientContact;
    private javax.swing.JLabel patientContactLbl;
    private javax.swing.JLabel patientContactLbl2;
    private javax.swing.JLabel patientDOBLbl2;
    private javax.swing.JButton patientDeleteBtn;
    private javax.swing.JTextField patientEmailID;
    private javax.swing.JLabel patientEmailIDLbl;
    private javax.swing.JLabel patientEmailIDLbl2;
    private javax.swing.JComboBox<String> patientGenderCombo;
    private javax.swing.JLabel patientGenderLbl;
    private javax.swing.JLabel patientGenderLbl2;
    private javax.swing.JTextField patientHeight;
    private javax.swing.JLabel patientHeightLbl;
    private javax.swing.JLabel patientHeightLbl1;
    private javax.swing.JButton patientHomeBtn;
    private javax.swing.JTextField patientHouse;
    private javax.swing.JLabel patientHouseLbl;
    private javax.swing.JLabel patientHouseLbl1;
    private javax.swing.JButton patientLogoutBtn;
    private javax.swing.JTextField patientName;
    private javax.swing.JLabel patientNameLbl;
    private javax.swing.JLabel patientNameLbl2;
    private javax.swing.JPasswordField patientPassword;
    private javax.swing.JTextField patientPatientID;
    private javax.swing.JLabel patientPatientIDLbl;
    private javax.swing.JLabel patientPatientIDLbl1;
    private javax.swing.JLabel patientPswdLbl;
    private javax.swing.JButton patientRegisterBtn;
    private javax.swing.JLabel patientRepswdLbl;
    private javax.swing.JTextField patientState;
    private javax.swing.JLabel patientStateLbl;
    private javax.swing.JLabel patientStateLbl1;
    private javax.swing.JTextField patientStreet;
    private javax.swing.JLabel patientStreetLbl;
    private javax.swing.JLabel patientStreetLbl1;
    private javax.swing.JTable patientTable;
    private javax.swing.JButton patientUpdateBtn;
    private javax.swing.JButton patientViewBtn;
    private javax.swing.JTextField patientWeight;
    private javax.swing.JLabel patientWeightLbl;
    private javax.swing.JLabel patientWeightLbl1;
    private javax.swing.JTextField patientZipCode;
    private javax.swing.JLabel patientZipCodeLbl;
    private javax.swing.JLabel patientZipCodeLbl1;
    private javax.swing.JPanel personAccountDetails;
    private javax.swing.JPanel personAddressDetails;
    private javax.swing.JButton personClearBtn;
    private javax.swing.JPanel personMedicalDetails;
    private javax.swing.JTabbedPane personModificationTab;
    private javax.swing.JPanel personPersonalDetails;
    // End of variables declaration//GEN-END:variables
}
