/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.Hospital;
import backend.HospitalDirectory;
import backend.House;
import backend.patient;
import backend.patientdirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sej
 */
public class HospitalRegistration extends javax.swing.JFrame {
    House residence = new House();
    HospitalDirectory hosdirect;
    patientdirectory patientdirect;
    
    

    /**
     * Creates new form HospitalRegistration
     */
    public HospitalRegistration(HospitalDirectory hosdirect,patientdirectory patientdirect) {
        initComponents();
        this.hosdirect=hosdirect;
        this.patientdirect=patientdirect;
        hosDisplayTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        hospitalHomeBtn = new javax.swing.JButton();
        hospitalLogoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hosName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hosLicenseNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hosNowards = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hosAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hosCommunity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        hosZipCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hosCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hosState = new javax.swing.JTextField();
        hospitalRegisterBtn = new javax.swing.JButton();
        hospitalUpdateBtn = new javax.swing.JButton();
        hospitalDeleteBtn = new javax.swing.JButton();
        hospitalViewBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        hosTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hospitalHomeBtn.setText("Home");
        hospitalHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalHomeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hospitalHomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 17, -1, -1));

        hospitalLogoutBtn.setText("Logout");
        hospitalLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalLogoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hospitalLogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 17, -1, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 15)); // NOI18N
        jLabel1.setText("Hospital Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 18, -1, -1));

        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 93, -1, -1));
        jPanel1.add(hosName, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 90, 140, -1));

        jLabel3.setText("License No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 154, -1, -1));

        hosLicenseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosLicenseNoActionPerformed(evt);
            }
        });
        jPanel1.add(hosLicenseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 151, 100, -1));

        jLabel9.setText("No. of Wards");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 216, -1, -1));
        jPanel1.add(hosNowards, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 210, 100, -1));

        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 93, -1, -1));
        jPanel1.add(hosAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 90, 155, -1));

        jLabel7.setText("Community");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 141, -1, -1));

        hosCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosCommunityActionPerformed(evt);
            }
        });
        jPanel1.add(hosCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 138, 102, -1));

        jLabel8.setText("Zip Code");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 192, -1, -1));

        hosZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosZipCodeActionPerformed(evt);
            }
        });
        jPanel1.add(hosZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 189, 100, -1));

        jLabel6.setText("City");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 243, -1, -1));
        jPanel1.add(hosCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 240, 100, -1));

        jLabel5.setText("State");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 281, -1, -1));
        jPanel1.add(hosState, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 281, 100, -1));

        hospitalRegisterBtn.setText("Register");
        hospitalRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalRegisterBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hospitalRegisterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 348, -1, -1));

        hospitalUpdateBtn.setText("Update");
        hospitalUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalUpdateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hospitalUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 348, -1, -1));

        hospitalDeleteBtn.setText("Delete");
        hospitalDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalDeleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hospitalDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 348, -1, -1));

        hospitalViewBtn.setText("View");
        hospitalViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalViewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hospitalViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 348, -1, -1));

        hosTable.setBackground(new java.awt.Color(204, 204, 204));
        hosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "License No", "Name", "Address", "Community", "City", "State", "Zip Code", "No of Wards"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(hosTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 435, 895, 262));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 398, 903, -1));

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalHomeBtnActionPerformed
        // TODO add your handling code here:
        MainFrame newMainFrame = new MainFrame();
        newMainFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_hospitalHomeBtnActionPerformed

    private void hospitalLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalLogoutBtnActionPerformed
        // TODO add your handling code here:
        LoginFrame newLoginPage = new LoginFrame();
        newLoginPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_hospitalLogoutBtnActionPerformed

    private void hosLicenseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosLicenseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hosLicenseNoActionPerformed

    private void hosCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hosCommunityActionPerformed

    private void hosZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hosZipCodeActionPerformed

    private void hospitalRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalRegisterBtnActionPerformed
        // TODO add your handling code here:
        Hospital hos=new Hospital();
        hos.setHosName(hosName.getText());
        hos.setHosLicNo(Integer.parseInt(hosLicenseNo.getText()));
        hos.setHosAddress((hosAddress.getText()));
        hos.residence.setCommunityName(hosCommunity.getText()) ;
        hos.residence.Zip = Integer.parseInt(hosZipCode.getText());
        hos.residence.newCity = hosCity.getText();
        hos.residence.state = hosState.getText();
        hos.setHosWard(Integer.parseInt(hosNowards.getText()));
        
        HospitalDirectory.hosdirect.add(hos);
        JOptionPane.showMessageDialog(this, "Person Successfully Added");
        hosDisplayTable();
        
        
        
    }//GEN-LAST:event_hospitalRegisterBtnActionPerformed

    private void hospitalUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalUpdateBtnActionPerformed
        // TODO add your handling code here:
      int selectedRowIndex1=hosTable.getSelectedRow();
      DefaultTableModel model1 = (DefaultTableModel) hosTable.getModel();
       Hospital selectedhos=(Hospital)model1.getValueAt(selectedRowIndex1, 0);
       selectedhos.setHosName(hosName.getText());
       selectedhos.setHosLicNo(Integer.parseInt(hosLicenseNo.getText()));
       selectedhos.setHosAddress((hosAddress.getText()));
        selectedhos.residence.setCommunityName(hosCommunity.getText()) ;
        selectedhos.residence.Zip = Integer.parseInt(hosZipCode.getText());
        selectedhos.residence.newCity = hosCity.getText();
        selectedhos.residence.state = hosState.getText();
        selectedhos.setHosWard(Integer.parseInt(hosNowards.getText()));
        hosDisplayTable();
      
    }//GEN-LAST:event_hospitalUpdateBtnActionPerformed

    private void hospitalDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalDeleteBtnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_hospitalDeleteBtnActionPerformed

    private void hospitalViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalViewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex1=hosTable.getSelectedRow();
        if(selectedRowIndex1<0){
            JOptionPane.showMessageDialog(this,"Please select a row to View");
            return;
        }
        DefaultTableModel model1 = (DefaultTableModel) hosTable.getModel();
        Hospital selectedhos=(Hospital)model1.getValueAt(selectedRowIndex1, 0);
        hosName.setText(selectedhos.getHosName());
        hosLicenseNo.setText(String.valueOf(selectedhos.getHosLicNo()));
        hosNowards.setText(String.valueOf(selectedhos.getHosWard()));
        hosZipCode.setText(String.valueOf(selectedhos.residence.getZip()));
        hosCommunity.setText(selectedhos.residence.getCommunityName());
        hosAddress.setText(selectedhos.getHosAddress());
        hosCity.setText(selectedhos.residence.getNewCity());
        hosState.setText(selectedhos.residence.getState());     
    }//GEN-LAST:event_hospitalViewBtnActionPerformed
 public void hosDisplayTable(){
     DefaultTableModel model1 = (DefaultTableModel) hosTable.getModel();
     model1.setRowCount(0);
     System.out.println("done");
     for(Hospital h1:HospitalDirectory.getHospdirect()){
        Object[] row=new Object[8];
        row[0]=h1;
        row[1]=h1.getHosName();
            row[2]=h1.getHosAddress();
            row[3]=h1.residence.getCommunityName();
            row[4]=h1.residence.getNewCity();
            row[5]=h1.residence.getState();
            row[6]=h1.residence.getZip();
            row[7]=h1.getHosWard();
            model1.addRow(row);
         
         
     }
 }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HospitalRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HospitalRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HospitalRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HospitalRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HospitalRegistration().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hosAddress;
    private javax.swing.JTextField hosCity;
    private javax.swing.JTextField hosCommunity;
    private javax.swing.JTextField hosLicenseNo;
    private javax.swing.JTextField hosName;
    private javax.swing.JTextField hosNowards;
    private javax.swing.JTextField hosState;
    private javax.swing.JTable hosTable;
    private javax.swing.JTextField hosZipCode;
    private javax.swing.JButton hospitalDeleteBtn;
    private javax.swing.JButton hospitalHomeBtn;
    private javax.swing.JButton hospitalLogoutBtn;
    private javax.swing.JButton hospitalRegisterBtn;
    private javax.swing.JButton hospitalUpdateBtn;
    private javax.swing.JButton hospitalViewBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
