/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.patient;
import backend.patientdirectory;
import backend.person;
import backend.personDirectory;
import backend.vitalsigns;
import backend.vitalsignshistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sej
 */
public class PatientRegistration extends javax.swing.JFrame {
    person per = new person();
    vitalsigns vitalsigns = new vitalsigns();
    vitalsignshistory vitaldirect;
    patientdirectory patientdirect;
    personDirectory persondirect;
    

    /**
     * Creates new form PatientRegistration
     */
    public PatientRegistration(patientdirectory patientdirect,personDirectory persondirect,vitalsignshistory vitaldirect) {
        initComponents();
        this.persondirect=persondirect;
        this.patientdirect=patientdirect;
        this.vitaldirect=vitaldirect;
        patientDispTable();
        personDispTable();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        patientContact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        patientEmailId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        patientGender = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        patientAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patientBloodgroup = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        patientHeight = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        patientWeight = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        patientHouse = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        patientCommunity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        patientCity = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        patientState = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        patientZipcode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        patientUsername = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        patientPassword = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        patientReenterpassword = new javax.swing.JTextField();
        registrationbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        viewbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        vitalTextArea = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        vitalsBP = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        vitalsTemp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1029, 989));

        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setPreferredSize(new java.awt.Dimension(1029, 989));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 15)); // NOI18N
        jLabel1.setText("Patient Registration");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 34, -1, -1));

        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 101, -1, -1));
        jPanel1.add(patientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 98, -1, -1));

        jLabel3.setText("Contact");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 146, -1, -1));
        jPanel1.add(patientContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel10.setText("Email ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        jPanel1.add(patientEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        jPanel1.add(patientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel15.setText("Age");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));
        jPanel1.add(patientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        jLabel8.setText("DOB");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel6.setText("BloodGrp");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 368, -1, -1));

        patientBloodgroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientBloodgroupActionPerformed(evt);
            }
        });
        jPanel1.add(patientBloodgroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 365, -1, -1));

        jLabel17.setText("Height");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 408, -1, -1));
        jPanel1.add(patientHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 408, -1, -1));

        jLabel18.setText("Weight");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 454, -1, -1));
        jPanel1.add(patientWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 451, -1, -1));

        jLabel7.setText("House");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 101, 50, 20));
        jPanel1.add(patientHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 98, -1, -1));

        jLabel19.setText("Community");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 146, -1, -1));
        jPanel1.add(patientCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 143, -1, -1));

        jLabel9.setText("City");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 187, -1, -1));
        jPanel1.add(patientCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 184, -1, -1));

        jLabel16.setText("State");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 232, -1, -1));
        jPanel1.add(patientState, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 229, -1, -1));

        jLabel12.setText("Zip Code");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 282, -1, -1));

        patientZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientZipcodeActionPerformed(evt);
            }
        });
        jPanel1.add(patientZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        jLabel13.setText("Username");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));
        jPanel1.add(patientUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        jLabel21.setText("Password");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));
        jPanel1.add(patientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        jLabel20.setText("Re-enter Password");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        patientReenterpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientReenterpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(patientReenterpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        registrationbtn.setText("REGISTER");
        registrationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationbtnActionPerformed(evt);
            }
        });
        jPanel1.add(registrationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, -1, -1));

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "name", "person id", "contact no", "email id", "gender", "age", "house", "community", "city", "state"
            }
        ));
        jScrollPane2.setViewportView(patientTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 970, 160));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1030, -1));

        viewbtn.setText("view");
        jPanel1.add(viewbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        updatebtn.setText("update");
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, -1));

        deletebtn.setText("delete");
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, -1, -1));

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "name", "patient id", "contact no", "email id", "gender", "age ", "community", "city", "blood group", "height", "weight"
            }
        ));
        jScrollPane3.setViewportView(personTable);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 970, 220));

        jButton5.setText("LogOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, -1, -1));

        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 33, -1, -1));

        jLabel23.setText("Enter Vital Signs");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 492, -1, -1));

        vitalTextArea.setColumns(20);
        vitalTextArea.setRows(5);
        jScrollPane4.setViewportView(vitalTextArea);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 374, 46));

        jLabel25.setText("Blood Pressure");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 98, -1));

        vitalsBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalsBPActionPerformed(evt);
            }
        });
        jPanel1.add(vitalsBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, 100, -1));

        jLabel24.setText("Body Temperature");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, -1, -1));
        jPanel1.add(vitalsTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 109, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void patientBloodgroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientBloodgroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientBloodgroupActionPerformed

    private void patientZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientZipcodeActionPerformed

    private void patientReenterpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientReenterpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientReenterpasswordActionPerformed

    private void registrationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationbtnActionPerformed
        // TODO add your handling code here:
        patient per1=new patient();
        per1.person.setName(patientName.getText());
        per1.person.setAge(Integer.parseInt(patientAge.getText()));
        per1.person.setContact(Long.parseLong(patientContact.getText());
        per1.person.setContactNo(Long.parseLong(patientContact.getText()));
        per1.person.setEmailId(patientEmailId.getText());
        per1.person.setGender(patientGender.getText());
        per1.person.residence.communityName= patientCommunity.getText();
        per1.person.residence.houseNo= Integer.parseInt(patientHouse.getText());
        per1.person.residence.zip = Integer.parseInt(patientZipcode.getText());
        per1.person.residence.newCity = patientCity.getText();
        per1.person.residence.state = patientState.getText();
        per1.setPatientId(Integer.parseInt(patientId.getText()));
        per1.setPatientUsername(patientUsername.getText());
        per1.setPatientpwd(patientPassword.getText());
        per1.vitalSigns.getBloodPressure();
        per1.vitalSigns.getBodyTemperature(Float.parseFloat(vitalsTemp));
        PatientDirectory.patientDir.add(pt1);
        JOptionPane.showMessageDialog(this, "Person Successfully Added");
        patientDispTable();

        
    }//GEN-LAST:event_registrationbtnActionPerformed

    private void vitalsBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalsBPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vitalsBPActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LoginFrame newLoginPage = new LoginFrame();
        newLoginPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        MainFrame newMainFrame = new MainFrame();
        newMainFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
    public void personDispTable(){
        DefaultTableModel model = (DefaultTableModel) personTable.getModel();
        model.setRowCount(0);
        System.out.println("Done");
        for (person p:persondirect.getpersondirect()){
            Object[] row=new Object[10];
            row[0]=p;
            row[1]=p.getPersonId();
            row[2]=p.getContact();
            row[3]=p.getEmailid();
            row[4]=p.getGender();
            row[5]=p.getAge();
            row[6]=p.residence.getHouse();
            row[7]=p.getCommunityname();
            row[8]=p.getNewCity();
            row[9]=p.getState();
            model.addRow(row);
            }
        
    }
    public void patientDispTable(){
        DefaultTableModel model1 = (DefaultTableModel) patientTable.getModel();
        model1.setRowCount(0);
        System.out.println("Done");
        for (patient p1:patientdirect.getpatientdirect()){
            Object[] row=new Object[10];
            row[0]=p1.person;
            row[1]=p1.getpatientId();
            row[2]=p1.person.getcontactNo();
            
            
            
            
        }
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField patientAge;
    private javax.swing.JTextField patientBloodgroup;
    private javax.swing.JTextField patientCity;
    private javax.swing.JTextField patientCommunity;
    private javax.swing.JTextField patientContact;
    private javax.swing.JTextField patientEmailId;
    private javax.swing.JTextField patientGender;
    private javax.swing.JTextField patientHeight;
    private javax.swing.JTextField patientHouse;
    private javax.swing.JTextField patientName;
    private javax.swing.JTextField patientPassword;
    private javax.swing.JTextField patientReenterpassword;
    private javax.swing.JTextField patientState;
    private javax.swing.JTable patientTable;
    private javax.swing.JTextField patientUsername;
    private javax.swing.JTextField patientWeight;
    private javax.swing.JTextField patientZipcode;
    private javax.swing.JTable personTable;
    private javax.swing.JButton registrationbtn;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton viewbtn;
    private javax.swing.JTextArea vitalTextArea;
    private javax.swing.JTextField vitalsBP;
    private javax.swing.JTextField vitalsTemp;
    // End of variables declaration//GEN-END:variables

    private void patientDispTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void personDispTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
