/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.person;
import backend.personDirectory;
import backend.city;
import backend.community;
//import backend.house;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sej
 */
public class PersonRegistration extends javax.swing.JFrame {
  personDirectory person;
    /**
     * Creates new form PersonRegistration
     */
    public PersonRegistration(personDirectory person) {
//        initComponents();
//        this.person=person;
//        personDispTable();
//    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        personHomeBtn = new javax.swing.JButton();
        personLogoutBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pcontact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pEmailid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pGender = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ppID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        pCommunity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pHouse = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pCity = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pState = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        pZipCode = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pUsername = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        pPswd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        pReenterPswd = new javax.swing.JTextField();
        personRegisterBtn = new javax.swing.JButton();
        personViewBtn = new javax.swing.JButton();
        personUpdateBtn = new javax.swing.JButton();
        personDeleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personHomeBtn.setText("Home");
        personHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personHomeBtnActionPerformed(evt);
            }
        });

        personLogoutBtn.setText("Logout");
        personLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personLogoutBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Contact");

        jLabel10.setText("Email ID");

        jLabel5.setText("Gender");

        pGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pGenderActionPerformed(evt);
            }
        });

        jLabel15.setText("Age");

        pAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pAgeActionPerformed(evt);
            }
        });

        jLabel11.setText("Person ID");

        ppID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppIDActionPerformed(evt);
            }
        });

        jLabel19.setText("Community");

        pCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCommunityActionPerformed(evt);
            }
        });

        jLabel7.setText("House");

        jLabel9.setText("City");

        pCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pCityActionPerformed(evt);
            }
        });

        jLabel16.setText("State");

        jLabel12.setText("Zip Code");

        pZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pZipCodeActionPerformed(evt);
            }
        });

        jLabel13.setText("Username");

        jLabel21.setText("Password");

        jLabel20.setText("Re-enter Password");

        pReenterPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pReenterPswdActionPerformed(evt);
            }
        });

        personRegisterBtn.setText("REGISTER");
        personRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personRegisterBtnActionPerformed(evt);
            }
        });

        personViewBtn.setText("View");
        personViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personViewBtnActionPerformed(evt);
            }
        });

        personUpdateBtn.setText("Update");

        personDeleteBtn.setText("Delete");
        personDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personDeleteBtnActionPerformed(evt);
            }
        });

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Person ID", "Contact No", "Email ID", "Gender", "Age", "House", "Community", "City", "State"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(personTable);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 15)); // NOI18N
        jLabel1.setText("Person Registration");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(personHomeBtn)
                .addGap(365, 365, 365)
                .addComponent(jLabel1)
                .addGap(248, 248, 248)
                .addComponent(personLogoutBtn))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addGap(96, 96, 96)
                .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(367, 367, 367)
                .addComponent(jLabel11)
                .addGap(54, 54, 54)
                .addComponent(ppID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel5)
                .addGap(87, 87, 87)
                .addComponent(pGender, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419)
                .addComponent(jLabel9)
                .addGap(87, 87, 87)
                .addComponent(pCity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(pAge, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(407, 407, 407)
                .addComponent(jLabel16)
                .addGap(80, 80, 80)
                .addComponent(pState, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(698, 698, 698)
                .addComponent(jLabel12)
                .addGap(56, 56, 56)
                .addComponent(pZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel13)
                .addGap(91, 91, 91)
                .addComponent(pUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel21)
                .addGap(92, 92, 92)
                .addComponent(pPswd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel20)
                .addGap(38, 38, 38)
                .addComponent(pReenterPswd, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(personRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(personViewBtn)
                .addGap(118, 118, 118)
                .addComponent(personUpdateBtn)
                .addGap(127, 127, 127)
                .addComponent(personDeleteBtn))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pEmailid, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(348, 348, 348)
                        .addComponent(jLabel7)
                        .addGap(73, 73, 73)
                        .addComponent(pHouse, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(367, 367, 367)
                        .addComponent(jLabel19)
                        .addGap(44, 44, 44)
                        .addComponent(pCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personHomeBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(personLogoutBtn))
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(ppID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel19)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pEmailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel15))
                    .addComponent(pAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(pZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(pUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(pPswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addComponent(pReenterPswd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(personRegisterBtn)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personViewBtn)
                    .addComponent(personUpdateBtn)
                    .addComponent(personDeleteBtn))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1065, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personHomeBtnActionPerformed
        // TODO add your handling code here:
        MainFrame newMainFrame=new MainFrame();
        newMainFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_personHomeBtnActionPerformed

    private void personLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personLogoutBtnActionPerformed
        // TODO add your handling code here:
        LoginFrame newLoginPage = new LoginFrame();
        newLoginPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_personLogoutBtnActionPerformed

    private void pGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pGenderActionPerformed

    private void pAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pAgeActionPerformed

    private void ppIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppIDActionPerformed

    private void pCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pCommunityActionPerformed

    private void pCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pCityActionPerformed

    private void pZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pZipCodeActionPerformed

    private void pReenterPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pReenterPswdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pReenterPswdActionPerformed

    private void personRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personRegisterBtnActionPerformed
        // TODO add your handling code here:
//        Person p2=new Person();
//        p2.setName(pName.)
//        per.setage(Integer.parseInt(pAge.getText()));
//        per.setContactNo(Long.parseLong(pcontact.getText()));
//        per.setEmailId(pEmailid.getText());
//        p1.setGender(pGender.getText());
//        p1.residence.communityName= pCommunity.getText();
//        p1.residence.houseNo= Integer.parseInt(pHouse.getText());
//        p1.residence.zip = Integer.parseInt(pZipCode.getText());
//        p1.residence.newCity = pCity.getText();
//        p1.residence.state = pState.getText();
//        p1.setPersonId(Integer.parseInt(ppID.getText()));
//        p1.setUserName(pUsername.getText());
//        p1.setPwd(pPswd.getText());
//        PersonDirectory.personDir.add(p1);
//        JOptionPane.showMessageDialog(this, "Person Successfully Added");
//        personDispTable();
    }//GEN-LAST:event_personRegisterBtnActionPerformed

    private void personViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personViewBtnActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex=personTable.getSelectedRow();
        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please select a row to delete");
            return;
        }
//        DefaultTableModel model = (DefaultTableModel) personTable.getModel();
////        Person selectedPerson=(Person)model.getValueAt(selectedRowIndex,0);
//        pName.setText(selectedPerson.getName());
//        ppID.setText(String.valueOf(selectedPerson.getPersonId()));
//        pcontact.setText(String.valueOf(selectedPerson.getContactNo()));
//        pHouse.setText(String.valueOf(selectedPerson.residence.getHouseNo()));
//        pEmailid.setText(selectedPerson.getEmailId());
//        pCommunity.setText(selectedPerson.residence.getCommunityName());
//        pAge.setText(String.valueOf(selectedPerson.getAge()));
//        pGender.setText(selectedPerson.getGender());
//        pCity.setText(selectedPerson.residence.getNewCity());
//        pState.setText(selectedPerson.residence.getState());
//        pZipCode.setText(String.valueOf(selectedPerson.residence.getZip()));
//        //        SimpleDateFormat strdate = new SimpleDateFormat("MMM-dd-yyyy");
//        //PhotoDisp.setIcon(selectedEmp.getIcon());
    }//GEN-LAST:event_personViewBtnActionPerformed

    private void personDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personDeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PersonRegistration().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pAge;
    private javax.swing.JTextField pCity;
    private javax.swing.JTextField pCommunity;
    private javax.swing.JTextField pEmailid;
    private javax.swing.JTextField pGender;
    private javax.swing.JTextField pHouse;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField pPswd;
    private javax.swing.JTextField pReenterPswd;
    private javax.swing.JTextField pState;
    private javax.swing.JTextField pUsername;
    private javax.swing.JTextField pZipCode;
    private javax.swing.JTextField pcontact;
    private javax.swing.JButton personDeleteBtn;
    private javax.swing.JButton personHomeBtn;
    private javax.swing.JButton personLogoutBtn;
    private javax.swing.JButton personRegisterBtn;
    private javax.swing.JTable personTable;
    private javax.swing.JButton personUpdateBtn;
    private javax.swing.JButton personViewBtn;
    private javax.swing.JTextField ppID;
    // End of variables declaration//GEN-END:variables
}
