/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package front;

import back.Employee;
import back.EmployeeData;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sej
 */

public class showpannel extends javax.swing.JPanel {

    /**
     * Creates new form showpannel
     */
    EmployeeData data;
    public showpannel(EmployeeData data) {
        initComponents();
        this.data = data;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NAME = new javax.swing.JTable();
        ViewButton = new javax.swing.JButton();
        Deletebutton = new javax.swing.JButton();
        StartD = new javax.swing.JTextField();
        lblStartDate = new javax.swing.JLabel();
        EmpId = new javax.swing.JTextField();
        lblEmployeeID = new javax.swing.JLabel();
        Position = new javax.swing.JTextField();
        lblPositionTitle = new javax.swing.JLabel();
        Level = new javax.swing.JTextField();
        lblLevel = new javax.swing.JLabel();
        TeamInfo = new javax.swing.JTextField();
        lblTeamInfo = new javax.swing.JLabel();
        CellPhone = new javax.swing.JTextField();
        lblCellPhoneNo = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        lblEmailAddress = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        Gender = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(195, 126, 126));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Employee Details");

        NAME.setBackground(new java.awt.Color(193, 210, 193));
        NAME.setFont(new java.awt.Font("Myanmar MN", 0, 13)); // NOI18N
        NAME.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NAME", "AGE", "GENDER", "DATE", "EMPLOYEEID", "POSITION TITLE", "LEVEL", "TEAM INFO", "CELL NO", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NAME.setToolTipText("");
        jScrollPane1.setViewportView(NAME);

        ViewButton.setBackground(new java.awt.Color(51, 153, 255));
        ViewButton.setText("VIEW");
        ViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButtonActionPerformed(evt);
            }
        });

        Deletebutton.setBackground(new java.awt.Color(51, 153, 255));
        Deletebutton.setText("DELETE");
        Deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebuttonActionPerformed(evt);
            }
        });

        StartD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDActionPerformed(evt);
            }
        });

        lblStartDate.setText("Start Date");

        EmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIdActionPerformed(evt);
            }
        });

        lblEmployeeID.setText("Employee ID");

        Position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionActionPerformed(evt);
            }
        });

        lblPositionTitle.setText("Position Title");

        Level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LevelActionPerformed(evt);
            }
        });

        lblLevel.setText("Level");

        TeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamInfoActionPerformed(evt);
            }
        });

        lblTeamInfo.setText("Team Info");

        CellPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CellPhoneActionPerformed(evt);
            }
        });

        lblCellPhoneNo.setText("Cell Phone No.");

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        lblEmailAddress.setText("Email Address");

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });

        lblAge.setText("Age");

        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });

        lblGender.setText("Gender");

        UpdateButton.setBackground(new java.awt.Color(51, 153, 255));
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblName)
                                            .addComponent(lblAge)
                                            .addComponent(lblGender, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(lblStartDate)
                                        .addComponent(lblEmployeeID)
                                        .addComponent(lblPositionTitle)
                                        .addComponent(lblLevel)
                                        .addComponent(lblTeamInfo)
                                        .addComponent(lblCellPhoneNo)
                                        .addComponent(lblEmailAddress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Deletebutton)
                                        .addGap(52, 52, 52)))
                                .addGap(171, 171, 171)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StartD, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmpId, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ViewButton)
                        .addGap(200, 200, 200)
                        .addComponent(UpdateButton)
                        .addGap(158, 158, 158))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Deletebutton)
                            .addComponent(ViewButton)
                            .addComponent(UpdateButton))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StartD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStartDate))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeID))
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPositionTitle)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLevel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(344, 344, 344))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTeamInfo))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCellPhoneNo))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailAddress))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void StartDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartDActionPerformed

    private void EmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpIdActionPerformed

    private void PositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PositionActionPerformed

    private void LevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LevelActionPerformed

    private void TeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamInfoActionPerformed

    private void CellPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CellPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CellPhoneActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void DeletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebuttonActionPerformed
       int selectedRowIndex = NAME.getSelectedRow();
        System.out.println(selectedRowIndex);
        if (selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"please select a row to delete");
            return; 
        }
        DefaultTableModel model = (DefaultTableModel) NAME.getModel();
        System.out.println(model.getValueAt(selectedRowIndex , 0));
        Employee selectedEmployee = (Employee) model.getValueAt(selectedRowIndex,0 );
        
        data.deletedata(selectedEmployee);
        
        JOptionPane.showMessageDialog(this,"data deleted");
        populateTable();

    }//GEN-LAST:event_DeletebuttonActionPerformed

    private void ViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButtonActionPerformed
        int selectedRowIndex = NAME.getSelectedRow();
        if (selectedRowIndex<0)
        {
            JOptionPane.showMessageDialog(this,"please select a row to delete");
            return; 
        }
        DefaultTableModel model = (DefaultTableModel) NAME.getModel();
        Employee selectedEmployee = (Employee) model.getValueAt(selectedRowIndex,0 );
        Name.setText(String.valueOf(selectedEmployee.getName()));
        Age.setText(String.valueOf(selectedEmployee.getAge()));
        Gender.setText(String.valueOf(selectedEmployee.getGender()));
        StartD.setText(String.valueOf(selectedEmployee.getDate()));
        EmpId.setText(String.valueOf(selectedEmployee.getEmployeeID()));
        Position.setText(String.valueOf(selectedEmployee.getPositionTitle()));
        Level.setText(selectedEmployee.getLevel());
        TeamInfo.setText(selectedEmployee.getTeamInfo());
        CellPhone.setText(String.valueOf(selectedEmployee.getCellPhoneNo()));
        Email.setText(String.valueOf(selectedEmployee.getEmail()));
        
        
       
        
    }//GEN-LAST:event_ViewButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) NAME.getModel();
        if(NAME.getSelectedRow() == 1)
        {
            String name = Name.getText();
            String age = Age.getText();
            String gender = Gender.getText();
            String startdate = StartD.getText();
            String employeeid = EmpId.getText();
            String position = Position.getText();
            String level = Level.getText();
            String teaminfo = TeamInfo.getText();
            String cellphone = CellPhone.getText();
            String emailid = Email.getText();
            model.setValueAt(name,NAME.getSelectedRow(),0);
            model.setValueAt(age, NAME.getSelectedRow(),1);
            model.setValueAt(gender,NAME.getSelectedRow(),2);
            model.setValueAt(startdate,NAME.getSelectedRow(),3);
            model.setValueAt(employeeid,NAME.getSelectedRow(),4);
            model.setValueAt(position,NAME.getSelectedRow(),5);
            model.setValueAt(level,NAME.getSelectedRow(),6);
            model.setValueAt(teaminfo,NAME.getSelectedRow(),7);
            model.setValueAt(cellphone,NAME.getSelectedRow(),8);
            model.setValueAt(emailid,NAME.getSelectedRow(),9);
            JOptionPane.showMessageDialog(this, "Update Successfully..");
        }
        else{
            if(NAME.getRowCount()==0) {
                JOptionPane.showMessageDialog(this, "Table is Empty..");
            }
        else{
                //  
                JOptionPane.showMessageDialog(this, "Please select Single Row For Update..");         
            }
        }
            
                
        

            
            
            
            
            
        
    }//GEN-LAST:event_UpdateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField CellPhone;
    private javax.swing.JButton Deletebutton;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField EmpId;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField Level;
    private javax.swing.JTable NAME;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Position;
    private javax.swing.JTextField StartD;
    private javax.swing.JTextField TeamInfo;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton ViewButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCellPhoneNo;
    private javax.swing.JLabel lblEmailAddress;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       DefaultTableModel model = (DefaultTableModel)NAME.getModel();
       model.setRowCount(0);
       for (Employee ed : data.getdata())
       {
        Object[] row = new Object[10];
    
        row[0] = ed;
        row[1] = ed.getAge();
        row[2] = ed.getGender();
        row[3] = ed.getDate();
        row[4] = ed.getEmployeeID();
        row[5] = ed.getPositionTitle();
        row[6] = ed.getLevel();
        row[7] = ed.getTeamInfo();
        row[8] = ed.getCellPhoneNo();
        row[9] = ed.getEmail();
   
        model.addRow(row);
        
       
       }
    }

}
        
                
                
           
   


    

